# NOTE: Make sure to update the 'TP_API_KEY' with a valid Developer key.
# To execute this docker-compose, store it in a file (e.g. testproject-agent.yaml) an run:
# docker-compose -f <file_name> up -d

version: "3.1"
services:
  testproject-persistent:
    image: testproject/agent:3.2.0
    container_name: testproject-persistent
    depends_on:
      - chrome
      - firefox
    ports:
      - "8585:8585"
    volumes:
      - "/var:/var/testproject/agent"
    environment:
      TP_API_KEY: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      TP_AGENT_ALIAS: "Docker Persistent"
      CHROME: "chrome:4444"
      FIREFOX: "firefox:4444"
  chrome:
    image: selenium/standalone-chrome
    volumes:
      - "/var/chrome:/dev/shm"
  firefox:
    image: selenium/standalone-firefox
    volumes:
      - "/var/firefox:/dev/shm"